module SearchForm
  module Filters
    # Renders a multi-select field for filtering by users who are editors.
    # This component extends `MultiSelectField` and populates its collection
    # by querying for all users associated with `editable_user_joins`.
    class EditorFilter < Fields::MultiSelectField
      # Initializes the EditorFilter.
      #
      # This component is specialized and hard-codes its own options for the
      # underlying `MultiSelectField`. The collection is generated by querying for all
      # distinct users who are editors, formatting their display name as
      # "Tutorial Name (email)" or "Full Name (email)", and then sorting the
      # list alphabetically.
      #
      # @param ** [Hash] Catches any other keyword arguments, which are passed
      #   to the superclass.
      def initialize(**)
        super(
          name: :editor_ids,
          label: I18n.t("basics.editors"),
          help_text: I18n.t("search.filters.helpdesks.editor_filter"),
          collection: editor_options,
          **
        )
      end

      private

        # This private method is responsible for building the collection.
        # Its logic is described in the initialize method's documentation.
        def editor_options
          User.joins(:editable_user_joins)
              .distinct
              .pluck(:id, :name, :name_in_tutorials, :email)
              .map do |id, name, name_in_tutorials, email|
                display_name = "#{name_in_tutorials.presence || name} (#{email})"
                [display_name, id]
              end
              .natural_sort_by(&:first)
        end
    end
  end
end
