module SearchForm
  module Filters
    # Renders a multi-select field for filtering by lectures. This component
    # extends `MultiSelectField` by implementing its optional radio button group
    # feature. It provides a concrete implementation for the `show_radio_group?`
    # and `render_radio_group` hooks defined by its parent.
    #
    # Additionally, it overrides the parent's default behavior by explicitly
    # disabling the "All" checkbox.
    class LectureScopeFilter < Fields::MultiSelectField
      # Initializes the LectureScopeFilter.
      #
      # This component is specialized and hard-codes its own options for the
      # underlying `MultiSelectField`. The collection is generated by querying for
      # all lectures and sorting them alphabetically by title.
      #
      # @param ** [Hash] Catches any other keyword arguments, which are passed
      #   to the superclass.
      def initialize(**)
        super(
          name: :lectures,
          label: I18n.t("basics.lectures"),
          help_text: I18n.t("search.filters.helpdesks.lecture_scope_filter"),
          collection: lecture_options,
          **
        )

        @show_radio_group = false
      end

      # A configuration method to enable the rendering of the radio button group.
      #
      # @return [self] Returns the component instance to allow for method chaining.
      def with_lecture_options
        @show_radio_group = true
        self
      end

      # A helper method for the template to determine if the radio button group
      # should be rendered.
      #
      # @return [Boolean] `true` if the radio group has been enabled via `with_lecture_options`.
      def show_radio_group?
        @show_radio_group
      end

      # Renders the `Controls::RadioGroup` component with a predefined set of
      # options ("All", "Subscribed", "Own Selection") and the necessary Stimulus
      # data attributes to control the select input.
      #
      # @return [String, nil] The rendered HTML for the radio group, or `nil` if it's not enabled.
      def render_radio_group
        return unless show_radio_group?

        render(Controls::RadioGroup.new(
                 form_state: form_state,
                 name: :lecture_option
               )) do |group|
          group.add_radio_button(
            value: "0",
            label: I18n.t("search.radio_buttons.lecture_scope_filter.all"),
            checked: true,
            disabled: false,
            inline: false,
            stimulus: { radio_toggle: true, controls_select: false }
          )
          group.add_radio_button(
            value: "1",
            label: I18n.t("search.radio_buttons.lecture_scope_filter.subscribed"),
            checked: false,
            disabled: false,
            inline: false,
            stimulus: { radio_toggle: true, controls_select: false }
          )
          group.add_radio_button(
            value: "2",
            label: I18n.t("search.radio_buttons.lecture_scope_filter.own_selection"),
            checked: false,
            disabled: false,
            inline: false,
            stimulus: { radio_toggle: true, controls_select: true }
          )
        end
      end

      # Overrides the parent class's hook to prevent the "All" checkbox from
      # ever being rendered for this specific component.
      #
      # @return [Boolean] Always returns `false`.
      def show_checkbox?
        false
      end

      private

        # This private method is responsible for building the collection.
        # Its logic is described in the initialize method's documentation.
        def lecture_options
          Lecture.includes(:course, :term)
                 .map { |l| [l.title, l.id] }
                 .natural_sort_by(&:first)
        end
    end
  end
end
