module SearchForm
  module Filters
    # Renders a multi-select field for filtering by programs.
    # This component extends `MultiSelectField` and populates its collection
    # by querying for all `Program` records.
    class ProgramFilter < Fields::MultiSelectField
      # Initializes the ProgramFilter.
      #
      # This component is specialized and hard-codes its own options for the
      # underlying `MultiSelectField`. The collection is generated by querying for all
      # programs, formatting their display name as "Subject Name: Program Name",
      # and then sorting the list alphabetically.
      #
      # @param ** [Hash] Catches any other keyword arguments, which are passed
      #   to the superclass.
      def initialize(**)
        super(
          name: :program_ids,
          label: I18n.t("basics.programs"),
          help_text: I18n.t("search.filters.helpdesks.program_filter"),
          collection: program_options,
          **
        )
      end

      private

        # This private method is responsible for building the collection.
        # Its logic is described in the initialize method's documentation.
        def program_options
          Program.includes(:subject, :translations, subject: :translations)
                 .map { |p| [p.name_with_subject, p.id] }
                 .natural_sort_by(&:first)
        end
    end
  end
end
