module SearchForm
  module Filters
    # Renders a grouped multi-select field for filtering by teachables (Courses
    # and their associated Lectures). This component extends `MultiSelectField`
    # with several key features:
    # - It builds a grouped collection suitable for `<optgroup>` tags, with
    #   courses as groups and lectures as options.
    # - It can optionally display a "with/without inheritance" radio button group.
    # - It provides custom data attributes for the "All" checkbox to interact
    #   with the radio button group via Stimulus.
    class TeachableFilter < Fields::MultiSelectField
      # Initializes the TeachableFilter.
      #
      # This component is specialized and hard-codes its own options. The collection
      # is generated by querying for all courses and their lectures, formatting
      # them into grouped options, and sorting them alphabetically.
      #
      # @param ** [Hash] Catches any other keyword arguments, which are passed
      #   to the superclass.
      def initialize(**)
        super(
          name: :teachable_ids,
          label: I18n.t("basics.associated_to"),
          help_text: I18n.t("search.filters.teachable_filter"),
          collection: grouped_teachable_list,
          **
        )

        @show_radio_group = false
      end

      # A configuration method to enable the rendering of the "with/without
      # inheritance" radio button group.
      #
      # @return [self] Returns the component instance to allow for method chaining.
      def with_inheritance_radios
        @show_radio_group = true
        self
      end

      # A hook for the parent template to determine if the radio button group
      # should be rendered.
      #
      # @return [Boolean] `true` if the radio group has been enabled.
      def show_radio_group?
        @show_radio_group
      end

      # Implements the parent's `render_radio_group` hook to render the
      # "with/without inheritance" radio buttons using the `Controls::RadioGroup`
      # component.
      #
      # @return [String, nil] The rendered HTML for the radio group, or `nil`.
      def render_radio_group
        return unless show_radio_group?

        render(Controls::RadioGroup.new(
                 form_state: form_state,
                 name: :teachable_inheritance
               )) do |group|
          group.add_radio_button(
            value: "1",
            label: I18n.t("basics.with_inheritance"),
            checked: true,
            disabled: true,
            inline: true,
            stimulus: { radio_toggle: true, controls_select: false }
          )
          group.add_radio_button(
            value: "0",
            label: I18n.t("basics.without_inheritance"),
            checked: false,
            disabled: true,
            inline: true,
            stimulus: { radio_toggle: true, controls_select: false }
          )
        end
      end

      # Overrides a hook from the `DataAttributesBuilder` to provide custom
      # `data` attributes for the "All" checkbox. These attributes are used by
      # the Stimulus controller to show/hide and enable/disable the inheritance
      # radio group when the "All" checkbox is toggled.
      #
      # @return [Hash] A hash of data attributes.
      def all_toggle_data_attributes
        {
          search_form_target: "allToggle",
          action: "change->search-form#toggleFromCheckbox change->search-form#toggleRadioGroup",
          toggle_radio_group: "teachable_inheritance",
          default_radio_value: "1" # Select "with_inheritance" by default
        }
      end

      private

        # This private method is responsible for building the grouped collection.
        # Its logic is described in the initialize method's documentation.
        def grouped_teachable_list
          course_label = I18n.t("basics.course")

          # Single query with proper eager loading
          courses_with_lectures = Course.includes(lectures: :term)
                                        .order(:title)

          courses_with_lectures.map do |course|
            lectures = [["#{course.short_title} #{course_label}", "Course-#{course.id}"]]

            course.lectures.natural_sort_by(&:short_title).each do |lecture|
              lectures << [lecture.short_title, "Lecture-#{lecture.id}"]
            end

            [course.title, lectures]
          end
        end
    end
  end
end
