# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 0

  - package-ecosystem: "docker"
    directories: "/docker/**/*"
    target-branch: "next"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 0
