# Docs:
# https://docs.github.com/en/code-security/dependabot
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-multi-ecosystem-updates
# https://docs.github.com/en/code-security/tutorials/secure-your-dependencies/automating-dependabot-with-github-actions#approve-a-pull-request

version: 2

multi-ecosystem-groups:
  regular-dependencies:
    schedule:
      interval: "cron"
      # Every Monday at 09:00
      cronjob: "0 9 * * 1"
      timezone: "Europe/Berlin"

  regular-infrastructure:
    schedule:
      interval: "cron"
      # Every Monday at 09:00
      cronjob: "0 9 * * 1"
      timezone: "Europe/Berlin"

  major-dependencies:
    schedule:
      interval: "cron"
      # Every 20 days at 09:00
      cronjob: "0 9 */20 * *"
      timezone: "Europe/Berlin"

  major-infrastructure:
    schedule:
      interval: "cron"
      # Every 20 days at 09:00
      cronjob: "0 9 */20 * *"
      timezone: "Europe/Berlin"

updates:
  ##############################################################################
  # REGULAR UPDATES
  # - security updates
  # - patch updates
  # - minor updates
  #
  # Auto-merge candidate after CI succeeds.
  ##############################################################################

  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "security"
    multi-ecosystem-group: "regular-dependencies"
    patterns: ["*"]
    commit-message:
      prefix: "deps: "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "security"
    multi-ecosystem-group: "regular-dependencies"
    patterns: ["*"]
    commit-message:
      prefix: "deps: "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    target-branch: "security"
    multi-ecosystem-group: "regular-infrastructure"
    patterns: ["*"]
    directories:
      - "/docker/**/*"
    commit-message:
      prefix: "deps (infra): "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "security"
    multi-ecosystem-group: "regular-infrastructure"
    patterns: ["*"]
    commit-message:
      prefix: "deps (infra): "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"


  ##############################################################################
  # MAJOR VERSION UPDATES
  #
  # Manual review recommended
  ##############################################################################

  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "security"
    multi-ecosystem-group: "major-dependencies"
    patterns: ["*"]
    commit-message:
      prefix: "deps (major): "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "security"
    multi-ecosystem-group: "major-dependencies"
    patterns: ["*"]
    commit-message:
      prefix: "deps (major): "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "all"

  - package-ecosystem: "docker"
    target-branch: "security"
    multi-ecosystem-group: "major-infrastructure"
    patterns: ["*"]
    directories:
      - "/docker/**/*"
    commit-message:
      prefix: "deps (infra, major): "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "security"
    multi-ecosystem-group: "major-infrastructure"
    ppatterns: ["*"]
    commit-message:
      prefix: "deps (infra, major): "
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "all"
