FROM cypress/included:13.11.0

COPY --chmod=0755 "./docker/test/entrypoint-cypress.sh" "/usr/src/app/entrypoint-cypress.sh"
ENTRYPOINT ["/usr/src/app/entrypoint-cypress.sh"]

# Install curl
RUN apt-get update && apt-get install curl -y
