---
EnableDefaultLinters: true
linters:
#  ErbSafety:
#    enabled: true
#    better_html_config: .better-html.yml
  Rubocop:
    enabled: false
    rubocop_config:
      inherit_from:
        - .rubocop.yml