# SEVERITY LEVELS
# In the GitHub CI/CD, we can only distinguish between "error" and "warning".
# In Rubocop this is much more granular: "info", "refactor", "convention",
# "warning", "error" and "fatal".
# From the docs: "The level is normally 'warning' for Lint and 'convention' for
# all the others, but this can be changed in user configuration."
# However, we don't want to set the severity for each cop individually, so instead
# we set the fatal level as "convention" in the CI/CD,
# i.e. severity: "convention" and up will be treated as an error on GitHub
# and below as warning such that the check will still pass (with a warning).
#
# Short:
# "convention" severity and up = Error on GitHub (CI/CD) -> check fails
# "refactor" severity and below = Warning on GitHub (CI/CD) -> check passes
#
# see the docs on severity
# https://docs.rubocop.org/rubocop/configuration.html#severity

# Rubocop defaults are by default required/included:
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
require:
  - rubocop-performance
  - rubocop-rails

# Ruby version is determined from the Gemfile.lock

#############################################
# Layout
#############################################

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 100

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

#############################################
# Metrics
#############################################

Metrics:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true

#############################################
# Style
#############################################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/RedundantReturn:
  AllowMultipleReturnValues: true

#############################################
# Performance
#############################################

Performance:
  Severity: refactor # a warning in CI/CD

Performance/FlatMap:
  Severity: warning # an error in CI/CD
