inherit_gem:
  rubocop-shopify: rubocop.yml

Layout/LineLength:
  Max: 80

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

