version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mampf
      POSTGRES_DB: mampf
  mampf:
    build: .
    ports:
      - 3000:3000
    entrypoint: /entrypoint.sh
    environment:
      RAILS_ENV: development
      PRODUCTION_DATABASE_ADAPTER: postgresql
      PRODUCTION_DATABASE_DATABASE: mampf
      PRODUCTION_DATABASE_USERNAME: mampf
#      PRODUCTION_DATABASE_PASSWORD: $DATABASE_PASSWORD
      PRODUCTION_DATABASE_HOST: db
      PRODUCTION_DATABASE_PORT: 5432
      MAILSERVER: localhost
      FROM_ADDRESS: mampf@localhost
      URL_HOST: localhost
#      RAILS_MASTER_KEY: $MASTER_KEY
      KEKS_SERVER: your_keks_server
      ERDBEERE_SERVER: your_erdbeere_server
      MUESLI_SERVER: your_muesli_server
      PROJECT_EMAIL: project@localhost
      MEDIA_FOLDER: mampf
