version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mampf
      POSTGRES_DB: mampf
      POSTGRES_PASSWORD: supersecret
    container_name: mampf_db
    volumes:
      - "./docker/create_interactions_db.sql:/docker-entrypoint-initdb.d/create_interactions_db.sql:ro"
  mampf:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mampf
    ports:
      - 3000:3000
    env_file: docker/docker.env
    depends_on:
      - db
