#!/usr/bin/env bash

# Registry credentials (GitHub Container Registry)
KAMAL_REGISTRY_PASSWORD=$GITHUB_TOKEN

# Rails secrets
RAILS_MASTER_KEY=$(cat config/master.key)

# Database
PRODUCTION_DATABASE_URL="postgresql://mampf:supersecret@mampf-db:5432/mampf"
POSTGRES_PASSWORD="supersecret"

# Email credentials
PROJECT_EMAIL_USERNAME="creativeusername"
PROJECT_EMAIL_PASSWORD="secretsecret"
PROJECT_EMAIL_MAILBOX="Other Users/mampf"
MAMPF_EMAIL_USERNAME="secret"
MAMPF_EMAIL_PASSWORD="secret"
FEEDBACK_EMAIL="mampf-feedback-mail"
PROJECT_NOTIFICATION_EMAIL="notificationmail"
