$('.readerItem').remove()
$('.mediaCommentsDecoration').remove()
$('#mediaCommentsSize').empty().append('(0)').data('size', 0)
$('#commentsIcon').removeClass('new-comment')
$('#noCommentsAlert').show()