class DefaultSetting
  KEKS_LINK = ENV['KEKS_SERVER']
  ERDBEERE_LINK = ENV['ERDBEERE_SERVER']
  MUESLI_LINK = ENV['MUESLI_SERVER']
  PROJECT_EMAIL = ENV['PROJECT_EMAIL']
  KEKS_QUESTION_LINK = KEKS_LINK + '/hitme#hide-options#hide-categories#question='
  BLOG_LINK = ENV['BLOG']
end
