version: '3.5'
services:
  master: &app
    build:
      context: git@github.com:fosterfarrell9/mampf.git#production
      dockerfile: docker/Dockerfile
    entrypoint: /usr/src/app/docker/entrypoint-master.sh
    image: mampf
    env_file: docker.env
    networks:
        - postgres
        - default
        - solr
    restart: always
    volumes:
      - "media_mampf:/mampf"
    depends_on:
      - redis
      - cache

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - default

  worker:
    <<: *app
    entrypoint: /usr/src/app/docker/entrypoint-worker.sh
    depends_on:
      - master
    environment:
      - VIRTUAL_HOST=localhost

  redis:
    restart: always
    image: redis:5-alpine
    networks:
      - default

  cache:
    restart: always
    image: memcached:alpine
    networks:
      - default

  solr:
    image: solr:8.1
    container_name: solr
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - /path/to/persistent/var_solr:/var/solr
    networks:
      - default
    restart: always

# Keeping the database separate from the docker setup is recommended.
# Manually create a docker network where the server can be reached and specify it here
networks:
    postgres:
        external: true

    workernet:

volumes:
    media_mampf:
        driver_opts:
            type: "nfs"
            o: "addr=<nfs server>,noatime,nolock,soft,vers=4.2,rw"
            device: ":/path/to/share"
