version: '3.2'
services:
  worker: &app
    build:
      context: git@github.com:fosterfarrell9/mampf.git#production
      dockerfile: docker/Dockerfile
    image: mampf
    env_file: docker.env
    networks:
        - postgres
        - solr
        - workernet
    restart: always
    volumes:
      - "media_mampf:/mampf"
    depends_on:
      - master
      - redis
      - cache

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - workernet

  master:
    <<: *app
    entrypoint: /usr/src/app/docker/entrypoint-master.sh
  
  redis:
    restart: always
    image: redis:5-alpine

  cache:
    restart: always
    image: memcached:alpine

  solr:
    image: solr:8.1
    container_name: solr
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - /path/to/persistent/var_solr:/var/solr
    networks:
      - solr
    restart: always

# Keeping the database separate from the docker setup is recommended.
# Manually create a docker network where the server can be reached and specify it here
networks:
    postgres:
        external:
            name: postgres

    workernet:

volumes:
    media_mampf:
        driver_opts:
            type: "nfs"
            o: "addr=<nfs server>:/path/to/share,noatime,nolock,soft,vers=4.2,rw"
            device: ":/docker/media_mampf"
