version: '3.4'
x-mampf:
  &mampf
  build:
    context: git@github.com:MaMpf-HD/mampf.git#production
    dockerfile: docker/production/Dockerfile
  env_file: docker.env
  networks:
    - solr
    - mampf
    - postgres
  restart: always
  depends_on:
    - redis
    - cache

services:
  master:
    <<: *mampf
    entrypoint: /usr/src/app/docker/production/entrypoint-master.sh
    volumes:
      - "media:/private/media:nocopy"
      - "submissions:/private/submissions:nocopy"
      - "public:/usr/src/app/public"
      - "caches:/caches:nocopy"

  worker:
    <<: *mampf
    entrypoint: /usr/src/app/docker/production/entrypoint-worker.sh
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - "media:/private/media:nocopy"
      - "submissions:/private/submissions:nocopy"
      - "caches:/caches:nocopy"

  proxy:
    build:
      context: git@github.com:MaMpf-HD/mampf.git#production
      dockerfile: docker/production/Dockerfile.proxy
    restart: always
    ports:
      - "127.0.0.1:3009:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "submissions:/private/submissions:ro,nocopy"
      - "public:/public"
    depends_on:
      - master
    networks:
      - mampf
  
  redis:
    restart: always
    image: redis:6-alpine
    networks:
      - mampf

  cache:
    restart: always
    image: memcached:alpine
    networks:
      - default

  solr:
    image: solr:8.11
    container_name: solr
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - /path/to/persistent/var_solr:/var/solr
    networks:
      - default
    restart: always

networks:
  postgres:
    external: true
  solr:
    external: true
  mampf:
    external: true

volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=krikkit,noatime,nolock,soft,vers=4.2,rw"
      device: ":/mampf/media/mampf"
  submissions:
    driver_opts:
      type: "nfs"
      o: "addr=krikkit,noatime,nolock,soft,vers=4.2,rw"
      device: ":/mampf/submissions/mampf"
  public:
  caches:
    driver_opts:
      type: "nfs"
      o: "addr=krikkit,noatime,nolock,soft,vers=4.2,rw"
      device: ":/mampf/caches/mampf"
