x-mampf:
  &mampf
  build:
    context: https://github.com/MaMpf-HD/mampf.git#${GIT_BRANCH:-main}
    dockerfile: docker/production/Dockerfile
  env_file: docker.env
  networks:
    - mampf
    - postgres
  restart: always
  depends_on:
    - redis
    - cache

services:
  sidekiq:
    <<: *mampf
    entrypoint: /usr/src/app/docker/production/entrypoint-sidekiq.sh
    volumes:
      - "media:/private/media:nocopy"
      - "submissions:/private/submissions:nocopy"
      - "caches:/caches:nocopy"

  app:
    <<: *mampf
    entrypoint: /usr/src/app/docker/production/entrypoint-app.sh
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "media:/private/media:nocopy"
      - "submissions:/private/submissions:nocopy"
      - "caches:/caches:nocopy"

  redis:
    restart: always
    image: redis:8.8-alpine
    networks:
      - mampf

  cache:
    restart: always
    image: memcached:1.6-alpine
    networks:
      - default

networks:
  postgres:
    external: true
  mampf:
    external: true

volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=yourfileserverdomain,noatime,nolock,soft,vers=4.2,rw"
      device: ":/mampf/media/mampf"
  submissions:
    driver_opts:
      type: "nfs"
      o: "addr=yourfileserverdomain,noatime,nolock,soft,vers=4.2,rw"
      device: ":/mampf/submissions/mampf"
  caches:
    driver_opts:
      type: "nfs"
      o: "addr=yourfileserverdomain,noatime,nolock,soft,vers=4.2,rw"
      device: ":/mampf/caches/mampf"