# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: de
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
locales: [de, en]

# Read and write translations.
data:
  read:
    - config/locales/**/*.%{locale}.yml

# Find translate calls
search:
  ## Root directories for relative keys resolution.
  # relative_roots:
  #   - app/controllers
  #   - app/helpers
  #   - app/mailers
  #   - app/presenters
  #   - app/views

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   *.jpg *.jpeg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less
  ##   *.yml *.json *.zip *.tar.gz *.swf *.flv *.mp3 *.wav *.flac *.webm *.mp4 *.ogg *.opus *.webp *.map *.xlsx
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos
    - app/assets/builds

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  # strict: true

  ## Allows adding ast_matchers for finding translations using the AST-scanners
  ## The available matchers are:
  ## - RailsModelMatcher
  ##     Matches ActiveRecord translations like
  ##     User.human_attribute_name(:email) and User.model_name.human
  ## - DefaultI18nSubjectMatcher
  ##     Matches ActionMailer's default_i18n_subject method
  ##
  ## To implement your own, please see `I18n::Tasks::Scanners::AstMatchers::BaseMatcher`.
  # ast_matchers:
  #   - 'I18n::Tasks::Scanners::AstMatchers::RailsModelMatcher'
  #   - 'I18n::Tasks::Scanners::AstMatchers::DefaultI18nSubjectMatcher'

## Do not consider these keys missing:
# ignore_missing:
  # - 'activerecord.errors.*'

## Consider these keys used:
ignore_unused:
  - 'activerecord.attributes.*'
  - 'activerecord.errors.*'
  - 'devise.*'
  - 'commontator.*'
# - '{devise,kaminari,will_paginate}.*'
# - 'simple_form.{yes,no}'
# - 'simple_form.{placeholders,hints,labels}.*'
# - 'simple_form.{error_notification,required}.:'

## Ignore these keys completely:
# ignore:
#  - kaminari.*
