media_publisher_job:
  cron: "*/1 * * * *"
  class: "MediaPublisher"
  queue: critical

submissions_cleaner_job:
  cron: "0 3 */1 * *"
  class: "SubmissionsCleaner"
  queue: critical

cache_cleaner_job:
  cron: "0 2 */1 * *"
  class: "CacheCleaner"
  queue: critical

user_cleaner_job:
  # at 4:00 AM, every day
  # This job has to run every day such that users will receive
  # respective warning emails (about their accounts being deleted) on time.
  cron: "0 4 * * *" 
  class: "UserCleanerJob"
  queue: critical
