media_publisher_job:
  cron: "*/1 * * * *"
  class: "MediaPublisher"
  queue: critical

submissions_cleaner_job:
  cron: "0 3 */1 * *"
  class: "SubmissionsCleaner"
  queue: critical

cache_cleaner_job:
  cron: "0 2 */1 * *"
  class: "CacheCleaner"
  queue: critical

user_cleaner_job:
  cron: "0 4 * * 1,4"
  class: "UserCleaner"
  queue: critical