test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

development:
  service: Disk
  root: <%= Rails.root.join("public/uploads/store/vignettes") %>

production:
  service: Disk
  root: "/private/media/vignettes"
  # https://discuss.rubyonrails.org/t/active-storage-in-production-lessons-learned-and-in-depth-look-at-how-it-works/83289#h-233-serving-files-through-rediret-mode-proxy-mode-and-public-mode-11
