# https://github.com/Shopify/erb_lint
glob: "**/*.{text,js}{+*,}.erb"
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
EnableDefaultLinters: true
linters:
  # Default linters are enabled by default, so we only need to specify the
  # ones we want to disable, as well as any additional ones we want to enable.
  # Note that we disable some purely HTML-related linters here since we use
  # HTML-ESLint for those (which is much more powerful).
  # erb_lint is mainly used for Ruby-related linting in any files that contain
  # ERB tags.
  SpaceIndentation:
    enabled: false
  SpaceInHtmlTag:
    enabled: false
  TrailingWhitespace:
    enabled: false
  ExtraNewLine:
    enabled: false
  FinalNewLine:
    enabled: false
  SelfClosingTag:
    enabled: false
  PartialInstanceVariable:
    enabled: true
  DeprecatedClasses:
    enabled: true
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .config/.rubocop.yml
        # Disable some rules that would require global context, since each
        # ruby statement (between ERB tags) is parsed and analyzed independently
        # of each other by erb_lint.
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
