{
 "title": "MaMpf General Overview",
 "description": "Dashboard for MaMpf",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Infrastructure and Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Traffic (app container)",
   "type": "timeseries",
   "description": "In/Out network traffic rate on the app container measured at the container network interface.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(ruby_mampf_app_network_receive_bytes[3m])*8",
     "legendFormat": "Network In"
    },
    {
     "expr": "rate(ruby_mampf_app_network_transmit_bytes[3m])",
     "legendFormat": "Network Out"
    }
   ]
  },
  {
   "title": "RAM Usage  %",
   "type": "gauge",
   "description": "RAM Usage in % (of Puma Processes)",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, role) (ruby_puma_process_ram_percent)",
     "legendFormat": "{{job}} - {{role}}"
    }
   ]
  },
  {
   "title": "CPU Usage in %",
   "type": "gauge",
   "description": "CPU Usage in % (of Puma Processes)",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, role) (ruby_puma_process_cpu_percent)",
     "legendFormat": "{{job}} - {{role}}"
    }
   ]
  },
  {
   "title": "CPU in % of Puma Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job, role) (ruby_puma_process_cpu_percent)",
     "legendFormat": "{{job}}  - {{role}}"
    }
   ]
  },
  {
   "title": "RAM Usage  %",
   "type": "timeseries",
   "description": "RAM Usage in %(of Puma Processes)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job, role)(ruby_puma_process_ram_percent)",
     "legendFormat": "{{job}} - {{role}}"
    }
   ]
  },
  {
   "title": "RAM Usage in MB",
   "type": "timeseries",
   "description": "RAM Usage in MB (of Puma Processes)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (job, role) (ruby_puma_process_ram_mb)",
     "legendFormat": "{{job}} - {{role}}"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "description": "Total HTTP request throughput across all controllers and actions, measured in requests per second over a 30-second window.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_request_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests that returned an error in the past 24 hours",
   "type": "timeseries",
   "description": "Total error requests (4xx/5xx) per controller action over a 24-hour window. Shows 0 for actions with no recent errors. Adjust the window size for production use.",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": "(\r\n  sum by (action, controller, status) (\r\n    ruby_http_requests_total{status=~\"4..|5..\"}\r\n    -\r\n    (\r\n      ruby_http_requests_total{status=~\"4..|5..\"} offset 24h\r\n      OR\r\n      ruby_http_requests_total{status=~\"4..|5..\"} * 0\r\n    )\r\n  )\r\n)\r\nOR\r\nlabel_replace(\r\n  sum by (action, controller) (ruby_http_requests_total) * 0,\r\n  \"status\", \"none\", \"\", \"\"\r\n)",
     "legendFormat": "Action: {{action}}, Controller: {{controller}}, Status: {{status}}"
    }
   ]
  },
  {
   "title": "Average SQL latency duration per request",
   "type": "timeseries",
   "description": "Average SQL query duration per controller action, aggregated over a 5-minute window. Shows 0 for actions with no recent requests. Adjust the window size for production use.",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (action, controller) (rate(ruby_http_request_sql_duration_seconds_sum[5m]))\r\n  /\r\n  (sum by (action, controller) (rate(ruby_http_request_duration_seconds_count[5m])) > 0)\r\n) * 1000\r\nOR on(action, controller)\r\n(\r\n  sum by (action, controller) (rate(ruby_http_request_duration_seconds_count[5m])) * 0\r\n)",
     "legendFormat": "Action: {{action}}, Controller: {{controller}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Average latency aggregated over a 5-minute window. Adjust the window size for production use.",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (action, controller) (rate(ruby_http_request_duration_seconds_sum[5m]))\r\n  /\r\n  sum by (action, controller) (rate(ruby_http_request_duration_seconds_count[5m]) > 0)\r\n) * 1000\r\nOR on(action, controller)\r\n(\r\n  sum by (action, controller) (rate(ruby_http_request_duration_seconds_count[5m])) * 0\r\n)",
     "legendFormat": "Action: {{action}}, Controller: {{controller}}"
    }
   ]
  },
  {
   "title": "Number of Logins in the past 24 hours",
   "type": "stat",
   "description": "Claculates the number of Logins in the past 24 hours with number of new sessions controller",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (controller, action) (\r\n  ruby_http_requests_total{controller=\"devise/sessions\", action=\"new\"}\r\n  -\r\n  (\r\n    ruby_http_requests_total{controller=\"devise/sessions\", action=\"new\"} offset 24h\r\n    OR\r\n    ruby_http_requests_total{controller=\"devise/sessions\", action=\"new\"} * 0\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lectures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_lecture_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests per Controller over the last 24 hours",
   "type": "timeseries",
   "description": "Total Requests per Controller with status code over the last 24 hours",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 42 },
   "targets": [
    {
     "expr": "sum by (controller, action, status) (\r\n  ruby_http_requests_total\r\n  -\r\n  (\r\n    ruby_http_requests_total offset 24h\r\n    OR\r\n    ruby_http_requests_total * 0\r\n  )\r\n)",
     "legendFormat": "Action: {{action}}, Controller: {{controller}}, Status: {{status}}"
    }
   ]
  },
  {
   "title": "Registered Users",
   "type": "stat",
   "description": "Number of registered users",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tags",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_tag_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Medium Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_uploaded_medium_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_consumption_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      { "panelId": 4 }
     ]
    },
    {
     "title": "Consumptions over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Medium Count over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      { "panelId": 7 }
     ]
    }
   ]
  },
  { "title": "Puma Metrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Booted Puma Workers",
   "type": "stat",
   "description": "Number of puma workers booted.\nOnly available in clustered mode.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_puma_booted_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Old Puma Workers",
   "type": "stat",
   "description": "Number of old puma workers.\nOnly available in clustered mode.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_puma_old_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Available Puma Workers",
   "type": "stat",
   "description": "Number of puma workers.\nOnly available in clustered mode.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_puma_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests waiting to be processed",
   "type": "stat",
   "description": "Number of requests waiting to be processed by a puma thread",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_puma_request_backlog", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Running Puma Threats",
   "type": "stat",
   "description": "Number of puma threads currently running",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_puma_running_threads", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Available Puma Threads",
   "type": "stat",
   "description": "Number of puma threads available at current scale",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_puma_thread_pool_capacity", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Max available Puma Threads",
   "type": "stat",
   "description": "Number of puma threads available at max scale",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ruby_puma_max_threads", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}