name: Linting

# Trigger each time HEAD branch is updated in a pull request
# see https://github.com/orgs/community/discussions/26366
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:

  rubocop:
    name: RuboCop (Ruby)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2 # to also fetch parent of PR (used to get changed files)

      - name: Get changed files
        id: rb-changed
        uses: ./.github/actions/changed_files/
        with:
          file-extensions: \.rb$

      - name: Set up Ruby 3
        if: ${{ steps.rb-changed.outputs.changed-files != ''}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true

      - name: Run RuboCop
        if: ${{ steps.rb-changed.outputs.changed-files != ''}}
        run: |
          echo "🚨 Running RuboCop version: $(bundle info rubocop | head -1)"
          bundle exec rubocop --config ./.config/.rubocop.yml --format github --fail-level 'convention' --force-exclusion -- $CHANGED_FILES

  eslint:
      name: ESLint (JS)
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v6
          with:
            fetch-depth: 2 # to also fetch parent of PR (used to get changed files)

        - name: Get changed files
          id: js-changed
          uses: ./.github/actions/changed_files/
          with:
            # .(mjs is only used for eslint.config.mjs as of January 2024)
            file-extensions: \.js$|\.mjs$|\.js.erb$

        - name: Setup Node.js
          if: ${{ steps.js-changed.outputs.changed-files != ''}}
          uses: actions/setup-node@v6
          with:
            node-version: '24' # End of Life (EOL): April 2028
            cache: 'yarn'

        - name: Install dependencies
          if: ${{ steps.js-changed.outputs.changed-files != ''}}
          run: yarn install

        # with ESLint v9 --ignore-path does not exist anymore
        # see [1] for the PR. However, my feeling for this is totally reflected
        # by [2]. Hopefully, it will come back in future versions.
        # [1] https://github.com/eslint/eslint/pull/16355
        # [2] https://github.com/eslint/eslint/issues/16264#issuecomment-1292858747
        - name: Run ESLint
          if: ${{ steps.js-changed.outputs.changed-files != ''}}
          run: |
            echo "🚨 Running ESLint version: $(yarn run --silent eslint --version)"
            yarn run eslint --config ./.config/eslint.mjs --max-warnings 0 --no-warn-ignored ${{ steps.js-changed.outputs.changed-files }}

  herb:
    name: Herb (HTML & ERB)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2 # to also fetch parent of PR (used to get changed files)

      - name: Get changed files
        id: js-changed
        uses: ./.github/actions/changed_files/
        with:
          file-extensions: \.html$|\.html.erb$

      - name: Setup Node.js
        if: ${{ steps.js-changed.outputs.changed-files != ''}}
        uses: actions/setup-node@v6
        with:
          node-version: '24' # End of Life (EOL): April 2028
          cache: 'yarn'

      - name: Install dependencies
        if: ${{ steps.js-changed.outputs.changed-files != ''}}
        run: yarn install

      - name: Run Herb Linter
        if: ${{ steps.js-changed.outputs.changed-files != ''}}
        run: |
          echo "🚨 Running Herb Lint version: $(yarn run herb-lint --version)"
          yarn run herb-lint ${{ steps.js-changed.outputs.changed-files }}

      - name: Run Herb Formatter
        if: ${{ steps.js-changed.outputs.changed-files != ''}}
        # we have to explicitly specify the config file here,
        # see issue: https://github.com/marcoroth/herb/issues/1177
        run: |
          echo "🚨 Running Herb Format version: $(yarn run herb-format --version)"
          yarn run herb-format --config-file ./.herb.yml --check ${{ steps.js-changed.outputs.changed-files }}
