name: Testing

on:
  push:
    branches:
      - main
      - dev
      - experimental
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  # For the setup idea using Docker Buildx, see StackOverflow answer [1].
  # [2] might also be very useful. [3] and [4] are generally about Docker
  # cache management (within GitHub Actions). Note that the GitHub Actions cache
  # is different from the GitHub Container Registry (ghcr).
  #
  # [1] https://stackoverflow.com/a/75544124/
  # [2] https://www.deploysentinel.com/blog/docker-buildx-cache-with-github-actions
  # [3] https://docs.docker.com/build/ci/github-actions/cache/
  # [4] https://docs.docker.com/build/cache/backends/
  unit-tests:
    name: Unit tests
    environment: testing
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      # see https://github.com/orgs/MaMpf-HD/packages?repo_name=mampf
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker images
        # As the docker-compose.yml file uses contexts like "./../..", we have
        # to change the working directory here.
        working-directory: docker/test
        # https://docs.docker.com/reference/cli/docker/buildx/bake/
        run: >
            IN_CI_CD=true docker buildx bake
            --allow=fs.read=/home/runner/work/mampf/mampf
            -f ./docker-compose.yml -f ./docker-compose.mampf-build-override.yml
            -f ./../../.github/workflows/docker-compose-cache.json

      - name: Run unit tests
        working-directory: docker/test
        run: >
          docker compose -f docker-compose.yml -f docker-compose.mampf-build-override.yml
          run --entrypoint="" mampf sh -c 
          "RAILS_ENV=test bundle exec rspec --format RSpec::Github::Formatter"

      - name: Report test coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  # Cypress end-to-end tests
  e2e-tests:
    name: e2e (Cypress)
    environment: testing
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # see https://github.com/orgs/MaMpf-HD/packages?repo_name=mampf
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        # As the docker-compose.yml file uses contexts like "./../..", we have
        # to change the working directory here.
        working-directory: docker/test
        run: >
          IN_CI_CD=true docker buildx bake
          --allow=fs.read=/home/runner/work/mampf/mampf
          -f ./docker-compose.yml -f ./docker-compose.mampf-build-override.yml
          -f ./cypress.yml
          -f ./../../.github/workflows/docker-compose-cache.json
      
      - name: Run Cypress tests
        working-directory: docker/test
        # "cypress run" is defined in the cypress.yml entrypoint
        run: > 
          docker compose
          -f ./docker-compose.yml -f docker-compose.mampf-build-override.yml
          -f ./cypress.yml
          run cypress
