name: Unit tests

on:
  push:
    branches:
      - main
      - mampf-next
      - production
      - experimental
  pull_request:

jobs:
  unit-test-job:
    name: Execute unit tests & upload to Codecov
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Pull docker images
      run: docker compose pull --ignore-buildable
      working-directory: docker/run_tests

    - name: Build docker containers
      working-directory: docker/run_tests
      run: docker compose build

    - name: Create and prepare test database
      working-directory: docker/run_tests
      run: docker compose run --entrypoint="" mampf 
            sh -c "RAILS_ENV=test rails db:create db:migrate db:test:prepare"

    - name: Prepare for test execution
      working-directory: docker/run_tests
      run: docker compose run --entrypoint="" mampf
            sh -c "RAILS_ENV=test rails assets:precompile && rake sunspot:reindex"

    - name: Run unit tests
      working-directory: docker/run_tests
      run: docker compose run --entrypoint="" mampf 
            sh -c "RAILS_ENV=test rails spec"

    - name: Send test coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        fail_ci_if_error: true
        verbose: true
