name: Unit tests

on:
  push:
    branches:
      - main
      - mampf-next
      - production
      - experimental
  pull_request:

jobs:
  unit-test-job:
    name: Execute unit tests & upload to Codecov
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Pull the latest image to build, and avoid caching pull-only images.
    # (docker pull is faster than caching in most cases.)
    - name: Pull docker images
      run: docker compose pull --ignore-buildable
      working-directory: docker/development

    # This action saves a list of existing images.
    # It also restores the cache if it exists.
    # see https://github.com/jpribyl/action-docker-layer-caching
    - name: Use Docker layer caching
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      continue-on-error: true

    - name: Build docker containers
      working-directory: docker/development
      run: docker compose build

    - name: Create and prepare test database
      working-directory: docker/development
      run: docker compose run mampf --entrypoint=""
            sh -c "RAILS_ENV=test rails db:create db:migrate db:test:prepare"

    - name: Prepare for test execution
      working-directory: docker/development
      run: docker compose run mampf --entrypoint=""
            sh -c "RAILS_ENV=test rake assets:precompile sunspot:reindex"

    - name: Run unit tests
      working-directory: docker/development
      run: docker compose run mampf --entrypoint=""
            sh -c "RAILS_ENV=test rails spec"

    - name: Send test coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        fail_ci_if_error: true
        verbose: true
