name: Unit tests

on:
  push:
    branches:
      - main
      - mampf-next
      - production
      - experimental
  pull_request:

jobs:
  unit-test-job:
    name: Execute unit tests & upload to Codecov
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Pull docker images
      run: docker compose pull --ignore-buildable
      working-directory: docker/run_cypress_tests

    - name: Use Docker layer caching # https://github.com/jpribyl/action-docker-layer-caching
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      continue-on-error: true

    - name: Build docker containers
      run: docker compose build
      working-directory: docker/run_cypress_tests
    - name: Create and migrate DB
      run: docker compose run --entrypoint "" mampf sh -c "rake db:create db:migrate db:test:prepare"
      working-directory: docker/run_cypress_tests
    - name: Reindex sunspot
      working-directory: docker/run_cypress_tests
      run: |
        docker compose run --entrypoint=""  mampf  sh -c "RAILS_ENV=test rake sunspot:reindex"

    - name: Run unit tests
      working-directory: docker/run_cypress_tests
      run: docker compose run --entrypoint="" mampf  sh -c "RAILS_ENV=test rails spec"

    - name: Send test coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage.xml
        fail_ci_if_error: true
        verbose: true
